api.bears.index:
    path: /api/beers/food/{food}
    controller: App\UI\Http\Rest\Controller\Beer\BeerIndexController::index
    methods: ['GET']

api.bears.show:
    path: /api/beers/{id}
    controller: App\UI\Http\Rest\Controller\Beer\BeerShowController::show
    methods: [ 'GET' ]

# config/routes.yaml
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }


kernel:
    resource: ../src/Kernel.php
    type: annotation